# Generated by Django 5.2.1 on 2025-05-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salons', models.PositiveIntegerField(default=0)),
                ('sample_sites', models.PositiveIntegerField(default=0, help_text='Count of unclaimed salons')),
                ('active_subscriptions', models.PositiveIntegerField(default=0)),
                ('pending_contacts', models.PositiveIntegerField(default=0, help_text="Salons with 'notContacted' status")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stats',
            },
        ),
    ]
