# Generated by Django 5.2.1 on 2025-05-18 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL Slug')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('image', models.ImageField(default='default.jpg', upload_to='business_pics', verbose_name='Business Image')),
                ('url', models.URLField(verbose_name='Business URL')),
                ('claimed', models.BooleanField(default=False, verbose_name='Claimed')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Claimed At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Business Address')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Type Name')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL Slug')),
                ('info', models.URLField(default='', verbose_name='Type Information URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Business Type',
                'verbose_name_plural': 'Business Types',
                'ordering': ['name'],
            },
        ),
    ]
