# Generated by Django 5.2.1 on 2025-05-18 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iframe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='business',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='iframe.type', verbose_name='Business Type'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name'], name='iframe_busi_name_dfab47_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='iframe_busi_slug_ea76de_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['type'], name='iframe_busi_type_id_38a853_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active'], name='iframe_busi_is_acti_089822_idx'),
        ),
    ]
