# Generated by Django 5.2.1 on 2025-05-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_cents', models.PositiveIntegerField(help_text='Price in cents (e.g., 7900 for $79.00)', verbose_name='Price (Cents)')),
                ('currency', models.CharField(default='usd', max_length=3, verbose_name='Currency')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in the plan', verbose_name='Features')),
                ('stripe_price_id', models.CharField(help_text='Stripe Price ID (e.g., price_xxxxxxxxxxxx)', max_length=255, unique=True, verbose_name='Stripe Price ID')),
                ('trial_period_days', models.PositiveIntegerField(default=0, help_text='Number of trial days (0 for no trial)', verbose_name='Trial Period (Days)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for new subscriptions', verbose_name='Is Active')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular for highlighting in UI', verbose_name='Is Popular')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
    ]
